apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener
  labels:
    app: urlshortener
  namespace: urlshortener
  annotations:
    monitoring: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urlshortener
  template:
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
      - image: kjell56/urlshortener
        name: urlshortener
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"

