apiVersion: v1
kind: Service
metadata:
  labels:
    app: urlshortener
  name: urlshortener
  namespace: urlshortener
spec:
  ports:
  - nodePort: 32500
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: urlshortener
  type: NodePort
